version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/main/resources/nba_shema_data.sql:/docker-entrypoint-initdb.d/init.sql
    #  - /usr/lib/postgresql/17/lib:/var/lib/postgresql/data
    networks:
      - spring-network
  app:
    container_name: spring_container
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/postgres?currentSchema=sport_results
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO : update

    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge